plot_me <- function(df,members,gender) {
  df %>%
    filter(Name %in% members,Gender==gender) %>%
    # group_by(Name,Year) %>%
    ggplot(aes(x=Year,y=Count)) +
    geom_point() +
    facet_wrap(~ Name) +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          plot.caption = element_text(hjust=1,face="italic"))
}

# remove the superfluous attribute generated by read_csv()
remove_attr_spec <- function(df) {
  attr(df,"spec") <- NULL
  invisible(df)
}

#
set_col_names <- function(df,old_col_names,new_col_names) {
  names(new_col_names) <- old_col_names
  rename_with(.data = df, .cols = old_col_names, .fn = function(x){new_col_names[x]})
}

#
change_col_types <- function(df) {
  df$Gender <- as.factor(str_to_upper(df$Gender))
  df$Year <- as.integer(df$Year)
  df$Count <- as.integer(df$Count)
  invisible(df)
}